//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TıbbiCihazSatışMerkezleri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmaDosyalarıdb
    {
        public int id { get; set; }
        public Nullable<int> Firmaid { get; set; }
        public byte[] TürkiyeTicaretSicilGazetesiOrnegi { get; set; }
        public byte[] VergiLevhasıOrnegi { get; set; }
        public byte[] İmzaSirküleriOrnegi { get; set; }
        public byte[] İşYeriAçmaveÇalıştırmaRuhsatı { get; set; }
        public string İşyeriRuhsatTarihi { get; set; }
        public string İşyeriRuhsatNo { get; set; }
        public string ÇalışmaAlanı { get; set; }
        public string DenemeOdası { get; set; }
        public string işyeriaçma { get; set; }
    
        public virtual FirmaBilgileridb FirmaBilgileridb { get; set; }
    }
}
