//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TıbbiCihazSatışMerkezleri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmaDurum
    {
        public int Kontrolid { get; set; }
        public Nullable<int> Firmaid { get; set; }
        public Nullable<int> Durum { get; set; }
        public string RedSebebi { get; set; }
        public string YapanKişi { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual FirmaBilgileridb FirmaBilgileridb { get; set; }
    }
}
