//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TıbbiCihazSatışMerkezleri.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContextEntitiess : DbContext
    {
        public ContextEntitiess()
            : base("name=ContextEntitiess")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FirmaBilgileridb> FirmaBilgileridb { get; set; }
        public virtual DbSet<ilceler> ilceler { get; set; }
        public virtual DbSet<iller> iller { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Vergi> Vergi { get; set; }
        public virtual DbSet<FirmaDosyalarıdb> FirmaDosyalarıdb { get; set; }
        public virtual DbSet<MesulMüdürüdb> MesulMüdürüdb { get; set; }
        public virtual DbSet<FirmaSahibidb> FirmaSahibidb { get; set; }
        public virtual DbSet<YetkiliBilgileri> YetkiliBilgileri { get; set; }
        public virtual DbSet<FirmaDurum> FirmaDurum { get; set; }
        public virtual DbSet<PersonelBilgileridb> PersonelBilgileridb { get; set; }
    }
}
