//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TıbbiCihazSatışMerkezleri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelBilgileridb
    {
        public int id { get; set; }
        public Nullable<int> Firmaid { get; set; }
        public string AdıSoyadı { get; set; }
        public string TcNo { get; set; }
        public string SertifikaTürü { get; set; }
        public string SertifikaTarihi { get; set; }
        public byte[] SertifikaDosyası { get; set; }
        public string SertifikaNo { get; set; }
    
        public virtual FirmaBilgileridb FirmaBilgileridb { get; set; }
    }
}
