//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TıbbiCihazSatışMerkezleri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vergi
    {
        public int id { get; set; }
        public string VergiNumarası { get; set; }
        public string FirmaAdi { get; set; }
        public string FirmaGenelMüdürlükAdresi { get; set; }
        public string VergiDairesi { get; set; }
    }
}
